# Generated by Django 3.2.4 on 2021-08-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TagModel',
            new_name='PostTagModel',
        ),
        migrations.AlterModelOptions(
            name='posttagmodel',
            options={'verbose_name': 'post tag', 'verbose_name_plural': 'post tags'},
        ),
    ]
