# Generated by Django 3.2.4 on 2021-09-16 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210915_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentmodel',
            options={'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
    ]
