# Generated by Django 3.2.4 on 2021-09-15 10:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='brandmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='shop.brandmodel', verbose_name='brand'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cars', to='shop.categorymodel', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='image',
            field=models.ImageField(upload_to='cars', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='long_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='long_description'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.FloatField(verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='short_description',
            field=models.TextField(verbose_name='short_description'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='tags',
            field=models.ManyToManyField(related_name='cars', to='shop.CarTagModel', verbose_name='tags'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='cartagmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='cartagmodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created_at'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='title',
            field=models.CharField(max_length=50, verbose_name='title'),
        ),
    ]
