# Generated by Django 3.2.4 on 2021-09-16 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210915_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars', verbose_name='image')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.carmodel', verbose_name='car')),
            ],
            options={
                'verbose_name': 'car image',
                'verbose_name_plural': 'car images',
            },
        ),
    ]
