# Generated by Django 3.2.4 on 2021-09-16 18:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_carimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='long_description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='long_description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='long_description_uz',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='long_description'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='short_description_ru',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='short_description_uz',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_en',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='categorymodel',
            name='title_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='title'),
        ),
    ]
