# Generated by Django 3.2.4 on 2021-09-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210916_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='real_price',
            field=models.FloatField(default=0, verbose_name='real_price'),
        ),
    ]
